// All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2026. For more information see LICENSE

package com.paysafe.payments.model.verification;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paysafe.payments.model.card.threeds.Authentication;
import com.paysafe.payments.model.common.GatewayResponse;
import com.paysafe.payments.model.common.error.Error;
import com.paysafe.payments.model.common.paymentfacilitator.PaymentFacilitator;
import com.paysafe.payments.model.common.profile.Profile;
import com.paysafe.payments.model.paymenthandle.enums.PaymentType;
import com.paysafe.payments.model.verification.enums.VerificationStatus;



/**
 * Contains details of a verification for a specific payment type
 */
public class Verification {

  @JsonProperty("id")
  private String id;
  @JsonProperty("merchantRefNum")
  private String merchantRefNum;
  @JsonProperty("paymentHandleToken")
  private String paymentHandleToken;
  @JsonProperty("customerIp")
  private String customerIp;
  @JsonProperty("dupCheck")
  private Boolean dupCheck;
  @JsonProperty("description")
  private String description;
  @JsonProperty("paymentFacilitator")
  private PaymentFacilitator paymentFacilitator;
  @JsonProperty("txnTime")
  private String txnTime;
  @JsonProperty("paymentType")
  private PaymentType paymentType;
  @JsonProperty("status")
  private VerificationStatus status;
  @JsonProperty("currencyCode")
  private String currencyCode;
  @JsonProperty("riskReasonCode")
  private List<Integer> riskReasonCode;
  @JsonProperty("gatewayResponse")
  private GatewayResponse gatewayResponse;
  @JsonProperty("profile")
  private Profile profile;
  @JsonProperty("authentication")
  private Authentication authentication;
  @JsonProperty("error")
  private Error error;
  @JsonProperty("cardSchemeTransactionId")
  private String cardSchemeTransactionId;

  public Verification() {
    super();
  }

  private Verification(final Builder builder) {
    setId(builder.id);
    setMerchantRefNum(builder.merchantRefNum);
    setPaymentHandleToken(builder.paymentHandleToken);
    setCustomerIp(builder.customerIp);
    setDupCheck(builder.dupCheck);
    setDescription(builder.description);
    setPaymentFacilitator(builder.paymentFacilitator);
    setTxnTime(builder.txnTime);
    setPaymentType(builder.paymentType);
    setStatus(builder.status);
    setCurrencyCode(builder.currencyCode);
    setRiskReasonCode(builder.riskReasonCode);
    setGatewayResponse(builder.gatewayResponse);
    setProfile(builder.profile);
    setAuthentication(builder.authentication);
    setError(builder.error);
    setCardSchemeTransactionId(builder.cardSchemeTransactionId);
  }

  public static Builder builder() {
    return new Builder();
  }


  public Verification id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The unique identifier for the verification transaction
   *
   * @return id
   */
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public Verification merchantRefNum(String merchantRefNum) {
    this.merchantRefNum = merchantRefNum;
    return this;
  }

  /**
   * The merchant reference number created by the merchant and submitted as part of the request
   *
   * @return merchantRefNum
   */
  public String getMerchantRefNum() {
    return merchantRefNum;
  }

  public void setMerchantRefNum(String merchantRefNum) {
    this.merchantRefNum = merchantRefNum;
  }


  public Verification paymentHandleToken(String paymentHandleToken) {
    this.paymentHandleToken = paymentHandleToken;
    return this;
  }

  /**
   * The payment token generated by Paysafe that will be used for the Verification request
   *
   * @return paymentHandleToken
   */
  public String getPaymentHandleToken() {
    return paymentHandleToken;
  }

  public void setPaymentHandleToken(String paymentHandleToken) {
    this.paymentHandleToken = paymentHandleToken;
  }


  public Verification customerIp(String customerIp) {
    this.customerIp = customerIp;
    return this;
  }

  /**
   * The customer's IP address
   *
   * @return customerIp
   */
  public String getCustomerIp() {
    return customerIp;
  }

  public void setCustomerIp(String customerIp) {
    this.customerIp = customerIp;
  }


  public Verification dupCheck(Boolean dupCheck) {
    this.dupCheck = dupCheck;
    return this;
  }

  /**
   * This validates that this request is not a duplicate. A request is considered a duplicate if the merchantRefNum has already been used in a previous request within the past 90 days.
   *
   * @return dupCheck
   */
  public Boolean getDupCheck() {
    return dupCheck;
  }

  public void setDupCheck(Boolean dupCheck) {
    this.dupCheck = dupCheck;
  }


  public Verification description(String description) {
    this.description = description;
    return this;
  }

  /**
   * This is a description of the transaction, provided by the merchant
   *
   * @return description
   */
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public Verification paymentFacilitator(PaymentFacilitator paymentFacilitator) {
    this.paymentFacilitator = paymentFacilitator;
    return this;
  }

  /**
   * Get paymentFacilitator
   *
   * @return paymentFacilitator
   */
  public PaymentFacilitator getPaymentFacilitator() {
    return paymentFacilitator;
  }

  public void setPaymentFacilitator(PaymentFacilitator paymentFacilitator) {
    this.paymentFacilitator = paymentFacilitator;
  }


  public Verification txnTime(String txnTime) {
    this.txnTime = txnTime;
    return this;
  }

  /**
   * The date and time of the verification transaction
   *
   * @return txnTime
   */
  public String getTxnTime() {
    return txnTime;
  }

  public void setTxnTime(String txnTime) {
    this.txnTime = txnTime;
  }


  public Verification paymentType(PaymentType paymentType) {
    this.paymentType = paymentType;
    return this;
  }

  /**
   * Get paymentType
   *
   * @return paymentType
   */
  public PaymentType getPaymentType() {
    return paymentType;
  }

  public void setPaymentType(PaymentType paymentType) {
    this.paymentType = paymentType;
  }


  public Verification status(VerificationStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status
   */
  public VerificationStatus getStatus() {
    return status;
  }

  public void setStatus(VerificationStatus status) {
    this.status = status;
  }


  public Verification currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  /**
   * This is the currency of the merchant account, e.g., USD or CAD. For a full list, see [Currency Codes](https://developer.paysafe.com/en/support/reference-information/codes/#currency-codes).
   *
   * @return currencyCode
   */
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public Verification riskReasonCode(List<Integer> riskReasonCode) {
    this.riskReasonCode = riskReasonCode;
    return this;
  }

  public Verification addRiskReasonCodeItem(Integer riskReasonCodeItem) {
    if (this.riskReasonCode == null) {
      this.riskReasonCode = new ArrayList<>();
    }
    this.riskReasonCode.add(riskReasonCodeItem);
    return this;
  }

  public Verification removeRiskReasonCodeItem(Integer riskReasonCodeItem) {
    if (riskReasonCodeItem != null && this.riskReasonCode != null) {
      this.riskReasonCode.remove(riskReasonCodeItem);
    }

    return this;
  }

  /**
   * List of risk-related reason codes
   *
   * @return riskReasonCode
   */
  public List<Integer> getRiskReasonCode() {
    return riskReasonCode;
  }

  public void setRiskReasonCode(List<Integer> riskReasonCode) {
    this.riskReasonCode = riskReasonCode;
  }


  public Verification gatewayResponse(GatewayResponse gatewayResponse) {
    this.gatewayResponse = gatewayResponse;
    return this;
  }

  /**
   * Get gatewayResponse
   *
   * @return gatewayResponse
   */
  public GatewayResponse getGatewayResponse() {
    return gatewayResponse;
  }

  public void setGatewayResponse(GatewayResponse gatewayResponse) {
    this.gatewayResponse = gatewayResponse;
  }


  public Verification profile(Profile profile) {
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   *
   * @return profile
   */
  public Profile getProfile() {
    return profile;
  }

  public void setProfile(Profile profile) {
    this.profile = profile;
  }


  public Verification authentication(Authentication authentication) {
    this.authentication = authentication;
    return this;
  }

  /**
   * Get authentication
   *
   * @return authentication
   */
  public Authentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(Authentication authentication) {
    this.authentication = authentication;
  }


  public Verification error(Error error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   *
   * @return error
   */
  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }


  public Verification cardSchemeTransactionId(String cardSchemeTransactionId) {
    this.cardSchemeTransactionId = cardSchemeTransactionId;
    return this;
  }

  /**
   * The transaction ID returned by the card scheme
   *
   * @return cardSchemeTransactionId
   */
  public String getCardSchemeTransactionId() {
    return cardSchemeTransactionId;
  }

  public void setCardSchemeTransactionId(String cardSchemeTransactionId) {
    this.cardSchemeTransactionId = cardSchemeTransactionId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Verification verification = (Verification) o;
    return Objects.equals(this.id, verification.id) &&
        Objects.equals(this.merchantRefNum, verification.merchantRefNum) &&
        Objects.equals(this.paymentHandleToken, verification.paymentHandleToken) &&
        Objects.equals(this.customerIp, verification.customerIp) &&
        Objects.equals(this.dupCheck, verification.dupCheck) &&
        Objects.equals(this.description, verification.description) &&
        Objects.equals(this.paymentFacilitator, verification.paymentFacilitator) &&
        Objects.equals(this.txnTime, verification.txnTime) &&
        Objects.equals(this.paymentType, verification.paymentType) &&
        Objects.equals(this.status, verification.status) &&
        Objects.equals(this.currencyCode, verification.currencyCode) &&
        Objects.equals(this.riskReasonCode, verification.riskReasonCode) &&
        Objects.equals(this.gatewayResponse, verification.gatewayResponse) &&
        Objects.equals(this.profile, verification.profile) &&
        Objects.equals(this.authentication, verification.authentication) &&
        Objects.equals(this.error, verification.error) &&
        Objects.equals(this.cardSchemeTransactionId, verification.cardSchemeTransactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, merchantRefNum, paymentHandleToken, customerIp, dupCheck, description, paymentFacilitator, txnTime, paymentType, status, currencyCode, riskReasonCode, gatewayResponse, profile, authentication, error, cardSchemeTransactionId);
  }

  @Override
  public String toString() {

    return "class Verification {\n"
        + "    id: " + toIndentedString(id) + "\n"
        + "    merchantRefNum: " + toIndentedString(merchantRefNum) + "\n"
        + "    paymentHandleToken: " + toIndentedString(paymentHandleToken) + "\n"
        + "    customerIp: " + toIndentedString(customerIp) + "\n"
        + "    dupCheck: " + toIndentedString(dupCheck) + "\n"
        + "    description: " + toIndentedString(description) + "\n"
        + "    paymentFacilitator: " + toIndentedString(paymentFacilitator) + "\n"
        + "    txnTime: " + toIndentedString(txnTime) + "\n"
        + "    paymentType: " + toIndentedString(paymentType) + "\n"
        + "    status: " + toIndentedString(status) + "\n"
        + "    currencyCode: " + toIndentedString(currencyCode) + "\n"
        + "    riskReasonCode: " + toIndentedString(riskReasonCode) + "\n"
        + "    gatewayResponse: " + toIndentedString(gatewayResponse) + "\n"
        + "    profile: " + toIndentedString(profile) + "\n"
        + "    authentication: " + toIndentedString(authentication) + "\n"
        + "    error: " + toIndentedString(error) + "\n"
        + "    cardSchemeTransactionId: " + toIndentedString(cardSchemeTransactionId) + "\n"
        + "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Contains details of a verification for a specific payment type builder static inner class.
   */
  public static final class Builder {
    private String id;
    private String merchantRefNum;
    private String paymentHandleToken;
    private String customerIp;
    private Boolean dupCheck;
    private String description;
    private PaymentFacilitator paymentFacilitator;
    private String txnTime;
    private PaymentType paymentType;
    private VerificationStatus status;
    private String currencyCode;
    private List<Integer> riskReasonCode;
    private GatewayResponse gatewayResponse;
    private Profile profile;
    private Authentication authentication;
    private Error error;
    private String cardSchemeTransactionId;

    private Builder() {
    }

    /**
     * The unique identifier for the verification transaction
     * <p>
     * Sets the id and returns a reference to this Builder enabling method chaining.
     *
     * @param id the id to set
     * @return a reference to this Builder
     */
    public Builder id(String id) {
      this.id = id;
      return this;
    }

    /**
     * The merchant reference number created by the merchant and submitted as part of the request
     * <p>
     * Sets the merchantRefNum and returns a reference to this Builder enabling method chaining.
     *
     * @param merchantRefNum the merchantRefNum to set
     * @return a reference to this Builder
     */
    public Builder merchantRefNum(String merchantRefNum) {
      this.merchantRefNum = merchantRefNum;
      return this;
    }

    /**
     * The payment token generated by Paysafe that will be used for the Verification request
     * <p>
     * Sets the paymentHandleToken and returns a reference to this Builder enabling method chaining.
     *
     * @param paymentHandleToken the paymentHandleToken to set
     * @return a reference to this Builder
     */
    public Builder paymentHandleToken(String paymentHandleToken) {
      this.paymentHandleToken = paymentHandleToken;
      return this;
    }

    /**
     * The customer's IP address
     * <p>
     * Sets the customerIp and returns a reference to this Builder enabling method chaining.
     *
     * @param customerIp the customerIp to set
     * @return a reference to this Builder
     */
    public Builder customerIp(String customerIp) {
      this.customerIp = customerIp;
      return this;
    }

    /**
     * This validates that this request is not a duplicate. A request is considered a duplicate if the merchantRefNum has already been used in a previous request within the past 90 days.
     * <p>
     * Sets the dupCheck and returns a reference to this Builder enabling method chaining.
     *
     * @param dupCheck the dupCheck to set
     * @return a reference to this Builder
     */
    public Builder dupCheck(Boolean dupCheck) {
      this.dupCheck = dupCheck;
      return this;
    }

    /**
     * This is a description of the transaction, provided by the merchant
     * <p>
     * Sets the description and returns a reference to this Builder enabling method chaining.
     *
     * @param description the description to set
     * @return a reference to this Builder
     */
    public Builder description(String description) {
      this.description = description;
      return this;
    }

    /**
     * Sets the paymentFacilitator and returns a reference to this Builder enabling method chaining.
     *
     * @param paymentFacilitator the paymentFacilitator to set
     * @return a reference to this Builder
     */
    public Builder paymentFacilitator(PaymentFacilitator paymentFacilitator) {
      this.paymentFacilitator = paymentFacilitator;
      return this;
    }

    /**
     * The date and time of the verification transaction
     * <p>
     * Sets the txnTime and returns a reference to this Builder enabling method chaining.
     *
     * @param txnTime the txnTime to set
     * @return a reference to this Builder
     */
    public Builder txnTime(String txnTime) {
      this.txnTime = txnTime;
      return this;
    }

    /**
     * Sets the paymentType and returns a reference to this Builder enabling method chaining.
     *
     * @param paymentType the paymentType to set
     * @return a reference to this Builder
     */
    public Builder paymentType(PaymentType paymentType) {
      this.paymentType = paymentType;
      return this;
    }

    /**
     * Sets the status and returns a reference to this Builder enabling method chaining.
     *
     * @param status the status to set
     * @return a reference to this Builder
     */
    public Builder status(VerificationStatus status) {
      this.status = status;
      return this;
    }

    /**
     * This is the currency of the merchant account, e.g., USD or CAD. For a full list, see [Currency Codes](https://developer.paysafe.com/en/support/reference-information/codes/#currency-codes).
     * <p>
     * Sets the currencyCode and returns a reference to this Builder enabling method chaining.
     *
     * @param currencyCode the currencyCode to set
     * @return a reference to this Builder
     */
    public Builder currencyCode(String currencyCode) {
      this.currencyCode = currencyCode;
      return this;
    }

    /**
     * List of risk-related reason codes
     * <p>
     * Sets the riskReasonCode and returns a reference to this Builder enabling method chaining.
     *
     * @param riskReasonCode the riskReasonCode to set
     * @return a reference to this Builder
     */
    public Builder riskReasonCode(List<Integer> riskReasonCode) {
      this.riskReasonCode = riskReasonCode;
      return this;
    }

    /**
     * Sets the gatewayResponse and returns a reference to this Builder enabling method chaining.
     *
     * @param gatewayResponse the gatewayResponse to set
     * @return a reference to this Builder
     */
    public Builder gatewayResponse(GatewayResponse gatewayResponse) {
      this.gatewayResponse = gatewayResponse;
      return this;
    }

    /**
     * Sets the profile and returns a reference to this Builder enabling method chaining.
     *
     * @param profile the profile to set
     * @return a reference to this Builder
     */
    public Builder profile(Profile profile) {
      this.profile = profile;
      return this;
    }

    /**
     * Sets the authentication and returns a reference to this Builder enabling method chaining.
     *
     * @param authentication the authentication to set
     * @return a reference to this Builder
     */
    public Builder authentication(Authentication authentication) {
      this.authentication = authentication;
      return this;
    }

    /**
     * Sets the error and returns a reference to this Builder enabling method chaining.
     *
     * @param error the error to set
     * @return a reference to this Builder
     */
    public Builder error(Error error) {
      this.error = error;
      return this;
    }

    /**
     * The transaction ID returned by the card scheme
     * <p>
     * Sets the cardSchemeTransactionId and returns a reference to this Builder enabling method chaining.
     *
     * @param cardSchemeTransactionId the cardSchemeTransactionId to set
     * @return a reference to this Builder
     */
    public Builder cardSchemeTransactionId(String cardSchemeTransactionId) {
      this.cardSchemeTransactionId = cardSchemeTransactionId;
      return this;
    }

    /**
     * Returns a Verification built from the parameters previously set.
     *
     * @return a Verification built with parameters of this Verification.Builder
     */
    public Verification build() {
      return new Verification(this);
    }
  }
}
